version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "15:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 10
